### ISSUE TITLE
nosignatures option no longer supported

### ISSUE THREAD

**Issue by phausamann** [xarray-contrib/sphinx-autosummary-accessors#36]
Hi, it seems like the `:nosignatures:` option is not working anymore with v0.2 (Sphinx 3.5).

This worked fine with v0.1.2 / Sphinx 2.4:
```
.. autosummary::
    :nosignatures:
    :template: autosummary/accessor_method.rst
```

Now I get the error:
```
File ".../sphinx_autosummary_accessors/autosummary.py", line 43, in create_documenter_from_template
    **options,
TypeError: generate_autosummary_content() got an unexpected keyword argument 'nosignatures'
```
